name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.0'
    - name: Build
      run: go build -v ./...
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3
      with:
        cosign-release: 'v2.2.3'
    - name: Store Cosign private key in a file
      run: 'echo "$COSIGN_KEY" > cosign.key'
      shell: bash
      env:
        COSIGN_KEY: ${{secrets.COSIGN_KEY}}
    - name: Release Binaries
      uses: goreleaser/goreleaser-action@v5
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{secrets.GH_PAT}}
        COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
