name: scan

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 7 10 * *'

jobs:
  virus-total:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build Binaries
        uses: goreleaser/goreleaser-action@v6
        with:
          version: 'v2.9.0'
          args: build --snapshot
      - name: List binaries
        run: |
          ls -lh ./dist/prs_*/prs
      - uses: dhth/composite-actions/.github/actions/scan-files@main
        with:
          files: './dist/prs_*/prs'
          vt-api-key: ${{ secrets.VT_API_KEY }}
